version: "3.8"

name: "WebCource"

services:
  test_api:
    image: web_cource_test
    container_name: test_api-aplication
    ports:
      - "5201:5201"
      - "5202:5202"
    environment:
      - RabbitMq__UserPassword=goblinusik111W
      - RabbitMq__UserLogin=FaITh725
      - RabbitMq__Host=rabbitmq
      - JwtSetting__SecretKey=SuperSecretKey8234064.SaltyForKey023.495
      - JwtSetting__Issuer=Issuer
      - JwtSetting__Audience=Audience
      - ConnectionStrings__SQLServerConnection=Server=ms-sql-server, 1433;Database=TestWeb;User=sa;Password=goblinusik111W;MultipleActiveResultSets=true;TrustServerCertificate=True;Integrated Security=False;
      - ConnectionStrings__RedisConnection=redis://:goblinusik111W@web-redis-db:6379
      - ConnectionStrings__AzuriteStorage=DefaultEndpointsProtocol=http;BlobEndpoint=http://localhost:10000/faith725;AccountName=faith725;AccountKey=ZGV2c3RvcmVhY2NvdW50Mw==
      - ASPNETCORE_URLS=https://+:5202;http://+:5201
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111W
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .\Certificates:/https:ros
    depends_on:
      - ms-sql-server
      - web-redis-db
      - rabbitmq
    networks:
      - rabbitmq_net
      - sql_server_net
      - redis_net

  authorize_api:
    image: web_cource_authorize
    container_name: authorize_api-aplication
    ports:
      - "5101:5101"
      - "5102:5102"
    environment:
      - RabbitMq__UserPassword=goblinusik111W
      - RabbitMq__UserLogin=FaITh725
      - RabbitMq__Host=rabbitmq
      - JwtSetting__SecretKey=SuperSecretKey8234064.SaltyForKey023.495
      - JwtSetting__Issuer=Issuer
      - JwtSetting__Audience=Audience
      - ConnectionStrings__SQLServerConnection=Server=ms-sql-server, 1433;Database=AuthWeb;User=sa;Password=goblinusik111W;MultipleActiveResultSets=true;TrustServerCertificate=True;Integrated Security=False;
      - ASPNETCORE_URLS=https://+:5102;http://+:5101
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111W
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .\Certificates:/https:ro
    depends_on:
      - ms-sql-server
      - rabbitmq
    networks:
      - rabbitmq_net
      - sql_server_net

  notification_api:
    image: web_cource_notification
    container_name: notification_api-application
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - RabbitMq__UserPassword=goblinusik111W
      - RabbitMq__UserLogin=FaITh725
      - RabbitMq__Host=rabbitmq
      - EmailSettings__ReciverEmail=courseproject2024@mail.ru
      - EmailSettings__Password=htmnrkmqU07kNjmFBSyB
      - ASPNETCORE_URLS=https://+:5002;http://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111W
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .\Certificates:/https:ro
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  azurite-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite-storage
    ports:
      - "10000:10000"
    environment:
      - "AZURITE_ACCOUNTS=faith725:ZGV2c3RvcmVhY2NvdW50Mw=="
    volumes:
      - blobs:/data

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: application_database
    ports:
      - "1333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=goblinusik111W
    volumes:
      - db_volume:/var/opt/mssql
    networks:
      - sql_server_net

  rabbitmq:
    image: rabbitmq:management
    container_name: message_broker_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=FaITh725
      - RABBITMQ_DEFAULT_PASS=goblinusik111W
    networks:
      - rabbitmq_net
  
  web-redis-db:
    image: redis/redis-stack:latest
    container_name: web-redis-db
    environment:
      - REDIS_PASSWORD=goblinusik111W
      - REDIS_ARGS=--requirepass goblinusik111W
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redis_net

networks:
  rabbitmq_net:
    driver: bridge
  sql_server_net:
    driver: bridge
  redis_net:
    driver: bridge

volumes:
  db_volume:
    driver: local
  blobs:
    driver: local